version: "3.8"

services:
  capitaria-api:
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    env_file:
      - ./.env
    ports:
      - "3000:80"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests

  capitaria-postgres:
    env_file:
      - ./.env
